FROM python:3-slim

RUN apt-get update && apt-get install build-essential -y

WORKDIR /app
COPY train/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY train/ccr_join.py ccr_join.py 
COPY train/ccr_train.py ccr_train.py
COPY train/run.sh run.sh

ENV SPARK_LOCAL_IP='localhost'