services:
  client:
    image: mcr.microsoft.com/cleanroom/ccf/ccf-provider-client:1.0.11
    ports:
      - "0:8080"
    environment:
      - WORKSPACE_DIR=/app/workspace
      - HOST_WORKSPACE_DIR=${AZCLI_CCF_PROVIDER_CLIENT_WORKSPACE_DIR}
      - IDENTITY_ENDPOINT=http://credentials-proxy:8080/token
      - IMDS_ENDPOINT="dummy_required_value"
      - CREDENTIALS_PROXY_USER=${AZCLI_CCF_PROVIDER_UID}:${AZCLI_CCF_PROVIDER_GID}
      - CREDENTIALS_PROXY_HOST_AZURE_VOLUME=${AZURE_FOLDER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${AZCLI_CCF_PROVIDER_CLIENT_WORKSPACE_DIR:-.}:/app/workspace
    depends_on:
    - credentials-proxy
  credentials-proxy:
    image: workleap/azure-cli-credentials-proxy
    ports:
      - "0:8080"
    volumes:
      - ${AZURE_FOLDER}:/app/.azure/
    user: "${AZCLI_CCF_PROVIDER_UID}:${AZCLI_CCF_PROVIDER_GID}"