services:
  client:
    image: mcr.microsoft.com/cleanroom/ccf/ccf-provider-client:1.0.11
    ports:
      - "0:8080"
    environment:
      - IDENTITY_ENDPOINT=${CREDENTIAL_PROXY_ENDPOINT}
      - IMDS_ENDPOINT="dummy_required_value"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
      name: ${NETWORK_NAME}
      external: true